config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  root 'static_pages#home'
  get 'static_pages/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq', to: 'static_pages#faq'
  get '/imprint', to: 'static_pages#imprint'
  get '/data-protection', to: 'static_pages#data_protection'
  get '/contact', to: 'static_pages#contact'
  get '/glossary', to: 'static_pages#glossary'

  resources :profiles, only: %i[index show]
  resources :questionnaire, only: %i[new create]
  get 'questionnaire/info', to: 'questionnaire#info'
  resources :posts, only: %i[index show]

  constraints Clearance::Constraints::SignedIn.new do
    namespace :admin do
      resources :profiles
      resources :dashboard, only: %i[index]
      resources :questionnaires, only: %i[index edit update destroy]
      resources :tags
      resources :treatment_methods
      resources :posts
    end
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def about; end

  def faq; end

  def imprint; end

  def data_protection; end

  def contact; end

  def glossary; end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<section class="section static">
  <div class="container about">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h1>
          Über uns
        </h1>
        <p class="is-size-5">Wir sind eine Gruppe queer-feministischer Aktivist*innen, die aus Patient*innen-Perspektive für Selbstbestimmung im Kontext gynäkologischer Behandlungen eintreten.</p>
        <div class="is-pulled-right m-md">
          <figure class="image">
            <%= image_tag("support-your-sisters.png", :alt => "Support your sisters illustration", :title => "Support your sisters Illustration, Fiona Tretau" ) %>
          </figure>
        </div>
        <p>Wir kämpfen einerseits um das Informationsrecht zum Thema Schwangerschaftsabbruch – dies ist ein wesentlicher Grund für unsere Initiative. Denn wir brauchen nicht nur einfach zugängliche und übersichtliche Informationen darüber, wer Abbrüche anbietet, sondern auch darüber, mit welcher Methode und zu welchem Preis die Behandlung durchgeführt wird und ob ein respektvoller und umsichtiger Umgang zu erwarten ist. Das gleiche gilt aber auch für andere gynäkologische Behandlungen, die teilweise zu unterschiedlichen Preisen angeboten werden, die bestimmten Personengruppen schwer zugänglich sind oder manchmal sogar verweigert werden, oder über die nicht vorurteilsfrei beraten wird.</p>
        <p>Egal ob für Schwangerschaftsabbrüche oder andere Behandlungen, wollen wir mit Gynformation eine bundesweites Verzeichnis von Gynäkolog*innen, Hebammen und gynäkologisch behandelnden Allgemeinärzt*innen zusammenstellen, die einen vertraulichen, unvoreingenommenen und professionellen Umgang pflegen und transparent über medizinische Behandlungsformen informieren. Unabhängig davon, ob du sexuell aktiv bist, mit wem und wie vielen Partner*innen du Sex hast, ob du Kinder haben möchtest oder nicht, ob du wenig Geld hast, mit bestimmten Pronomen angesprochen werden möchtest, ein Kopftuch trägst, wie du aussiehst, ob du HIV-positiv bist, Erfahrungen mit (sexualisierter) Gewalt gemacht hast, egal, welches Geschlecht dir bei der Geburt zugewiesen wurde, ob du beschnitten bist, du Deutsch sprichst oder nicht, welchen Aufenthaltsstatus du hast, ob du Drogen nimmst, einen Rollstuhl benutzt, Sexarbeiter*in bist, oder oder oder – du solltest immer professionelle Unterstützung bei deiner Entscheidungsfindung erhalten.</p>
        <h2 class="subtitle">Teile deine positiven Erfahrungen, empowere dich und andere</h2>
        <p>Die Gynäkologie ist ein medizinischer Fachbereich, in dem ein einfühlsamer Umgang besonders wichtig ist – denn oft geht es um Fragen der eigenen Identität, Sexualität und Lebensplanung und die Untersuchungen sind häufig körperlich sensibel und intim. Übergriffiges, diskriminierendes oder unachtsames Verhalten innerhalb der Gynäkologie können als besonders grenzüberschreitend erlebt werden. Deshalb haben wir entschieden – inspiriert von dem französischen Kollektiv <%= link_to 'Gyn&Co', 'https://gynandco.wordpress.com/', target: '_blank' %> – eine Liste von behandelnden Personen in Deutschland aufzubauen, die diskriminierungsfrei arbeiten, ein Bewusstsein für Konsens bei der Behandlung haben und Informationen und Raum für selbstbestimmte Entscheidungen geben.</p>
        <p>Dieses Verzeichnis wird ausschließlich auf der Grundlage von individuellen Empfehlungen nach und nach aufgebaut und erweitert. Es soll jeder Person dabei helfen, möglichst schnell die individuell richtige Adresse zu finden. Darum sammelt Gynformation positive Empfehlungen und ist keine Seite zur generellen/negativen Bewertung von gynäkologisch behandelnden Personen. Wenn du selbst gute Erfahrungen gemacht hast, teile sie bitte mit uns, indem du  <%= link_to 'diesen Fragebogen', new_questionnaire_url %> ausfüllst.</p>
        <h2 class="subtitle">Arbeit als Kollektiv</h2> 
        <p>Wir werten jeden Fragebogen einzeln und anonymisiert aus, bevor wir die Informationen zur empfohlenen Person auf unserer <%= link_to 'kommentierten Adressliste', profiles_url %> zur Verfügung stellen. Wir arbeiten bewusst als Kollektiv, d.h. wir besprechen uns über inhaltliche und strukturelle Fragen in der Gruppe und versuchen dabei möglichst viele Erfahrungen und Stimmen einzubeziehen. In unserem Auswertungs-Team sind ausschließlich Menschen, die selbst Erfahrungen mit gynäkologischer Behandlung als Patient*innen gemacht haben/machen, mit unterschiedlichen Hintergründen und Expertisen. Wenn du mehr zu dem Auswertungsprozess der eingehenden Fragebögen oder unseren Kriterien wissen möchtest, findest du in unseren <%= link_to 'FAQs', faq_path %> einige Antworten. Ein Manifest zu unserer Grundhaltung und den Prinzipien, auf denen dieses Projekt aufbaut, haben wir <%= link_to 'hier', post_path(1) %> veröffentlicht.</p>
        <p>Die Selbstbestimmung über unseren Körper und unsere Sexualität hat außerdem ein großes Potenzial zum kollektiven Empowerment beizutragen: darum wollen wir mit der Rubrik <%= link_to 'Glossar', glossary_path %> und unserem <%= link_to 'Expert*innen-Blog', posts_path %> Anstöße geben, sich Wissen über Gynäkologie und den eigenen Körper anzueignen.</p>
        <p>Diese Seite befindet sich gerade noch im Aufbau und ist nicht perfekt. Wir freuen uns deshalb über konstruktives Feedback an <%= mail_to 'kontakt@gynformation.de', 'kontakt@gynformation.de' %>. So arbeiten wir zum Beispiel aktuell noch an Übersetzungen in Leichte Sprache, ins Englische und andere Sprachen, an der Barrierefreiheit der Seite und einigen Funktionen. Wenn du uns dabei unterstützen kannst, weil du z.B. übersetzen oder programmieren kannst, dann freuen wir uns über motivierte <%= link_to 'Neuzugänge', faq_path(anchor: 'faq-contact-participate') %>.</p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contact.html.erb
<section class="section static">
  <div class="container imprint">
    <div class="columns">
      <div class="column is-8 is-offset-2 is-size-6">
        <h1>
          Contact
        </h1>
        <div class="is-pulled-right m-md">
          <figure class="image">
            <%= image_tag("catcalls.png", :alt => "Cats against catcalls illustration", :title => "Cats against catcalls Illustration, Fiona Tretau") %>
          </figure>
        </div>
        <p>Ihr erreicht uns per Mail über <%= mail_to 'kontakt@gynformation.de', 'kontakt@gynformation.de' %></p>
      </div>
    </div>
</section>

app/views/static_pages/home.html.erb
<div class='section home'>
  <div class='container'>
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <div class="tile is-ancestor">
          <div class="tile is-parent is-8">
            <article class="tile is-child has-primary-border about-box">
              <p><%= t('.about.teaser') %></p>
              <%= link_to t('.about.button') , about_path, class: 'button is-primary' %>
            </article>
          </div>
          <div class="tile is-parent">
            <article class="tile is-child">
              <figure class="image">
                <%= image_tag("treatment_chair.png", :alt => "Illustration eines gynäkologischen Behandlungsstuhls", :title => "Illustration eines gynäkologischen Behandlungsstuhls, Fiona Tretau") %>
              </figure>
            </article>
          </div>
        </div>
        <div class="tile is-ancestor">
          <div class="tile is-parent m-t-lg">
            <article class="tile is-child has-danger-border cta-box">
              <p><%= t('.search.teaser') %></p>
              <%= link_to t('.search.button') , profiles_url, class: 'button is-danger' %>
            </article>
          </div>
          <div class="tile is-parent m-t-lg">
            <article class="tile is-child has-danger-border cta-box">
              <p><%= t('.recommend.teaser') %></p>
              <%= link_to t('.recommend.button'), new_questionnaire_url, class: 'button is-danger' %>
            </article>
          </div>
        </div>
        <div class="columns">
          <div class="column is-10 is-offset-1">
            <div class="tile is-ancestor">
              <%= link_to posts_path do %>
                <div class="tile is-parent m-t-lg">
                  <article class="tile is-child link-box has-primary-border">
                    <h2><%= t('.blog.headline') %></h2>
                    <p><%= t('.blog.teaser') %></p>
                  </article>
                </div>
              <% end %>
              <%= link_to faq_path do %>
                <div class="tile is-parent m-t-lg">
                  <article class="tile is-child link-box has-primary-border">
                    <h2><%= t('.faq.headline') %></h2>
                    <p><%= t('.faq.teaser') %></p>
                  </article>
                </div>
              <% end %>
              <%= link_to glossary_path do %>
                <div class="tile is-parent m-t-lg">
                  <article class="tile is-child link-box has-primary-border">
                    <h2><%= t('.glossar.headline') %></h2>
                    <p><%= t('.glossar.teaser') %></p>
                  </article>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/imprint.html.erb
<section class="section static">
  <div class="container imprint">
    <div class="columns">
      <div class="column is-8 is-offset-2 is-size-6">
        <h1>
          <%= t('.headline') %>
        </h1>
        <address class='m-t-md'>
          Gynformation<br>
          c/o femrep e.V.<br>
          Schäferstraße 26<br>
          20355 Hamburg<br>
          Mail: <%= mail_to 'kontakt@gynformation.de', 'kontakt@gynformation.de' %>
        </address>
        <div class='m-t-xl'>
          <p class='has-text-weight-bold'>Illustrationen: Fiona Tretau</p>
        </div>
      </div>
    </div>
  </div>
</section>