config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  root 'static_pages#home'
  get 'static_pages/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq', to: 'static_pages#faq'
  get '/imprint', to: 'static_pages#imprint'
  get '/data-protection', to: 'static_pages#data_protection'
  get '/contact', to: 'static_pages#contact'
  get '/glossary', to: 'static_pages#glossary'

  resources :profiles, only: %i[index show]
  resources :questionnaire, only: %i[new create]
  get 'questionnaire/info', to: 'questionnaire#info'
  resources :posts, only: %i[index show]

  constraints Clearance::Constraints::SignedIn.new do
    namespace :admin do
      resources :profiles
      resources :dashboard, only: %i[index]
      resources :questionnaires, only: %i[index edit update destroy]
      resources :tags
      resources :treatment_methods
      resources :posts
    end
  end
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  include Filterable
  has_one :address, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :profile_treatments, dependent: :destroy
  has_many :treatment_methods, through: :profile_treatments
  attribute :published, :boolean, default: false

  accepts_nested_attributes_for :address

  delegate :street, :city, :state, :zip, to: :address, allow_nil: true

  enum category: %i[gynecologist general_practitioner midwife]

  validates :last_name, presence: true

  scope :filter_by_tag, ->(key) { joins(:tags).where('tags.key' => key) }
  scope :filter_by_state, lambda { |state|
                            includes(:address)
                              .where('addresses.state' => state)
                          }
  scope :filter_by_treatment_method, lambda { |key|
                                       joins(:treatment_methods)
                                         .where('treatment_methods.key' => key)
                                     }
  scope :filter_by_published, ->(published) { where published: published }
  scope :filter_by_last_name,
        ->(last_name) { where('last_name like ?', "#{last_name}%") }

  def tag_list
    tags.map(&:name).join(', ')
  end
end

app/controllers/admin/profiles_controller.rb
# frozen_string_literal: true

class Admin::ProfilesController < ApplicationController
  layout 'admin'

  def new
    @profile = Profile.new
    @profile.build_address
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to admin_profile_path(@profile)
    else
      render 'new'
    end
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update_attributes(profile_params)
      flash[:success] = 'Profile updated'
      redirect_to admin_profile_path(@profile)
    else
      render 'edit'
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    redirect_to admin_dashboard_index_path
  end

  private

  def profile_params
    params.require(:profile).permit(
      :first_name, :last_name, :website, :category, :published, :comment,
      :language, :tag_list, :tag, { tag_ids: [] }, :tag_ids, :phone_number,
      :accessibility, :financing_of_treatments,
      :treatment_method_id, { treatment_method_ids: [] }, :treatment_method_ids,
      address_attributes: %i[id profile_id street zip city state],
      health_insurance: []
    )
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  def index
    @pagy, @profiles = pagy(Profile.filter(
      params.slice(:tag, :state, :treatment_method)
    ).where(published: true).order(:last_name))
  end

  def show
    @profile = Profile.where(published: true).find(params[:id])
  end

  private

  def profile_params
    params.require(:profile).permit(:tag, :state, :treatment_method)
  end
end

app/helpers/admin/profiles_helper.rb
# frozen_string_literal: true

module Admin::ProfilesHelper
end

app/helpers/profiles_helper.rb
# frozen_string_literal: true

module ProfilesHelper
  def options_for_categories
    {
      t('profile.categories.general_practitioner') => :general_practitioner,
      t('profile.categories.gynecologist') => :gynecologist,
      t('profile.categories.midwife') => :midwife
    }
  end

  def state_name(iso_code)
    state_hash = Address.states.select { |state| state[:iso_code] == iso_code }
    state_hash.first[:name] unless state_hash.empty?
  end
end

app/views/profiles/_filter_bar.html.erb
<section role='search'>
  <fieldset class="profile-search">
    <%= form_with url: profiles_path, method: 'get' do |form| %>
      <div class='select is-fullwidth m-t-sm'>
        <%= form.select('tag', options_for_select(Tag.all.collect {|tag| [tag.name[I18n.locale.to_s], tag.key] }, selected: params[:tag]), {prompt: I18n.t('profile.select_a_tag') })  %>
      </div>
      <div class='select is-fullwidth m-t-sm'>
        <%= form.select('treatment_method', options_for_select(TreatmentMethod.all.collect {|treatment_method| [treatment_method.name[I18n.locale.to_s], treatment_method.key] }, selected: params[:treatment_method]), {prompt: I18n.t('profile.select_a_treatment_method') })  %>
      </div>
      <div class='select is-fullwidth m-t-sm'>
        <%= form.select('state', options_for_select(Address.states.collect  { |state| [state[:name], state[:iso_code]] }, selected: params[:state]), { prompt: I18n.t('profile.select_a_state') })  %>
      </div>
      <%= form.submit I18n.t('profile.filter'), class: 'button is-danger is-fullwidth m-t-sm' %>
    <% end %>
  </fieldset>
</section>

app/views/profiles/_profile.html.erb
<li id="profile-<%=profile.id%>" %>
  <div class='box profile__element'>
    <div class="content">
      <h3><%= profile.first_name %> <%= profile.last_name %></h3>
      <p><%= I18n.t("profile.categories.#{profile.category}") %></p>
      <p><%= profile.street %>, <%= profile.zip %> <%= profile.city %>, <%= state_name(profile.state) %></p>
      <h4><%= t('profile.accessibility')%></h4>
      <p><%= profile.accessibility %></p>
      <h4><%= t('profile.language')%></h4>
      <p><%= profile.language %></p>
      <h4><%= t('profile.recommended_for') %></h4>
      <div class="tags">
        <%= raw profile.tags.map(&:name).map { |tag_name| content_tag(:span, tag_name[I18n.locale.to_s], class: 'tag')}.join() %>
      </div>
      <h4><%= t('profile.treatment_methods') %></h4>
      <div class="tags">
        <p><%= raw profile.treatment_methods.map(&:name).map { |treatment_method_name| content_tag(:span, treatment_method_name[I18n.locale.to_s], class: 'tag ')}.join() %></p>
      </div>
      <%= link_to t('profile.more'), profile_path(profile.id), class: 'button is-danger profile-detail-btn' %>
    </div>
  </div>
</li>

app/views/profiles/index.html.erb
<section class="section profile">
  <div class="container">
    <div class="columns">
      <div class="column is-8 is-offset-2">
        <h2 class="search-headline">Ich suche eine behandelnde Person, die empfohlen wurde für ... </h2>
        <%= render 'filter_bar' %>
        <ul class='profile__list'>
          <% if @profiles.length > 0 %>
            <% @profiles.each do |profile| %>
              <%= render profile %>
            <% end %>
          <% else %>
            <p><%= t('profile.no_results') %></p>
          <% end %>
        </ul>
        <div class="m-t-md">
          <%= pagy_bulma_nav(@pagy).html_safe if @pagy.pages > 1 %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/profiles/show.html.erb
 <%= render 'shared/profile_detail_view', profile: @profile  %>