config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :passwords, controller: 'clearance/passwords', only: %i[create new]
  resource :session, controller: 'clearance/sessions', only: [:create]

  resources :users, controller: 'clearance/users', only: [:create] do
    resource :password,
             controller: 'clearance/passwords',
             only: %i[create edit update]
  end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  root 'static_pages#home'
  get 'static_pages/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/faq', to: 'static_pages#faq'
  get '/imprint', to: 'static_pages#imprint'
  get '/data-protection', to: 'static_pages#data_protection'
  get '/contact', to: 'static_pages#contact'
  get '/glossary', to: 'static_pages#glossary'

  resources :profiles, only: %i[index show]
  resources :questionnaire, only: %i[new create]
  get 'questionnaire/info', to: 'questionnaire#info'
  resources :posts, only: %i[index show]

  constraints Clearance::Constraints::SignedIn.new do
    namespace :admin do
      resources :profiles
      resources :dashboard, only: %i[index]
      resources :questionnaires, only: %i[index edit update destroy]
      resources :tags
      resources :treatment_methods
      resources :posts
    end
  end
end

app/controllers/admin/dashboard_controller.rb
# frozen_string_literal: true

class Admin::DashboardController < ApplicationController
  layout 'admin'
  def index
    @pagy, @profiles = pagy(
      Profile.filter(params.slice(:published, :last_name))
    )
  end
end

app/helpers/admin/dashboard_helper.rb
# frozen_string_literal: true

module Admin::DashboardHelper
  def options_for_published
    {
      t('profile.published.all') => nil,
      t('profile.published.true') => true,
      t('profile.published.false') => false
    }
  end
end

app/views/admin/dashboard/_filter_bar.html.erb
<section role='search' class="m-b-md">
  <fieldset class="m-t-md">
    <%= form_with url: admin_dashboard_index_path, method: 'get' do |form| %>
      <div class="field is-grouped is-horizontal">
        <div class="control">
          <div class='select'>
            <%= form.select(:published, options_for_published, selected: params[:published]) %>
          </div>
        </div>
        <div class="control">
          <%= form.text_field :last_name, class: 'input', placeholder: t('.placeholder_last_name'), value: params[:last_name]  %>
        </div>
        <div class="control">
          <%= form.submit I18n.t('profile.filter'), class: 'button is-primary' %>
        </div>
      </div>
    <% end %>
  </fieldset>
</section>

app/views/admin/dashboard/index.html.erb
<div class='section'>
  <div class='container'>
    <div class="columns">
      <div class="column is-10 is-offset-1">
        <%= link_to t('admin.new_profile'), new_admin_profile_path, class: 'button is-primary' %>
        <%= render 'filter_bar' %>
        <table class='table is-striped is-fullwidth'>
          <thead>
            <tr>
              <th>Name</th>
              <th>Bundesland</th>
              <th>Veröffentlicht</th>
              <th>Aktionen</th>
            </tr>
          </thead>
          <tbody>
            <% @profiles.each do |profile| %>
              <tr>
                <td><%= profile.first_name %> <%= profile.last_name %></td>
                <td><%= profile.state %></td>
                <td>
                  <span class="icon">
                    <% if profile.published %>
                      <i class="fa fa-check"></i>
                    <% else %>
                      <i class="fa fa-times"></i>
                    <% end %>
                  </span>
                </td>
                <td>
                  <%= link_to edit_admin_profile_path(profile.id), data: { test: "edit-profile-link" } do %>
                    <span class="icon">
                      <i class="fa fa-edit" title=<%= t('profile.edit') %>></i>
                    </span>
                  <% end %>
                  <%= link_to admin_profile_path(profile.id), data: { test: "show-profile-link" } do %>
                    <span class="icon">
                      <i class="fa fa-eye" title=<%= t('profile.show') %>></i>
                    </span>
                  <% end %>
                  <%= link_to admin_profile_path(profile.id), method: :delete, data: { confirm: "Are you sure?", test: "delete-profile-link" } do %>
                    <span class="icon">
                      <i class="fa fa-trash" title=<%= t('profile.delete') %>></i>
                    </span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= pagy_bulma_nav(@pagy).html_safe if @pagy.pages > 1 %>
      </div>
    </div>
  </div>
</div>